export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  ADMIN_LOGIN: '/admin-login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  REPORT: '/report',
  HISTORY: '/my-complaints',
  TRACK: '/track',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  ADMIN: '/admin',
  ADMIN_COMPLAINTS: '/admin/complaints',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_SETTINGS: '/admin/settings',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
};
