/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'surface-variant':            '#e4e1ee',
        'on-surface':                 '#1b1b24',
        'on-primary-container':       '#dad7ff',
        'background':                 '#fcf8ff',
        'on-background':              '#1b1b24',
        'surface-container':          '#f0ecf9',
        'surface-container-low':      '#f5f2ff',
        'surface-container-high':     '#eae6f4',
        'surface-container-highest':  '#e4e1ee',
        'surface-container-lowest':   '#ffffff',
        'surface-bright':             '#fcf8ff',
        'surface-dim':                '#dcd8e5',
        'surface':                    '#fcf8ff',
        'outline':                    '#777587',
        'outline-variant':            '#c7c4d8',
        'on-surface-variant':         '#464555',
        'tertiary-container':         '#a44100',
        'on-tertiary-container':      '#ffd2be',
        'tertiary-fixed':             '#ffdbcc',
        'tertiary-fixed-dim':         '#ffb695',
        'on-tertiary-fixed':          '#351000',
        'on-tertiary-fixed-variant':  '#7b2f00',
        'primary-fixed-dim':          '#c3c0ff',
        'on-secondary-fixed':         '#00174b',
        'on-secondary':               '#ffffff',
        'inverse-primary':            '#c3c0ff',
        'secondary-fixed':            '#dbe1ff',
        'on-tertiary':                '#ffffff',
        'primary':                    '#3525cd',
        'on-primary-fixed-variant':   '#3323cc',
        'secondary-container':        '#316bf3',
        'on-secondary-fixed-variant': '#003ea8',
        'primary-container':          '#4f46e5',
        'primary-fixed':              '#e2dfff',
        'on-primary-fixed':           '#0f0069',
        'secondary-fixed-dim':        '#b4c5ff',
        'on-secondary-container':     '#fefcff',
        'inverse-surface':            '#302f39',
        'inverse-on-surface':         '#f3effc',
        'surface-tint':               '#4d44e3',
        'secondary':                  '#0051d5',
        'tertiary':                   '#7e3000',
        'on-primary':                 '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      spacing: {
        xs:   '4px',
        sm:   '8px',
        base: '4px',
        md:   '16px',
        lg:   '24px',
        xl:   '32px',
        '2xl':'48px',
        '3xl':'64px',
        'gutter': '20px',
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        hanken: ['"Hanken Grotesk"', 'sans-serif'],
        geist: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg':         ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md':        ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':           ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm':           ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
