# Generated by Django 5.0.6 on 2026-06-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='detected_damage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
