# Generated by Django 5.0.6 on 2026-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_detected_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
