# Generated by Django 5.0.6 on 2026-06-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='severity_level',
            field=models.CharField(default='Low', max_length=20),
        ),
    ]
