# Generated by Django 5.0.6 on 2026-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_severity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
