# Generated by Django 5.0.6 on 2026-06-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_escalated_complaint_escalation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
