# Generated by Django 5.0.6 on 2026-06-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='repaired/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Escalated', 'Escalated')], default='Pending', max_length=20),
        ),
    ]
