# Generated by Django 5.2.15 on 2026-06-27 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_assigned_at_complaint_assigned_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='complainttimeline',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='expected_completion',
            new_name='estimated_completion',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='work_scheduled_at',
            new_name='work_scheduled_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_department',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='remarks',
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_bounding_box',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complainttimeline',
            name='assigned_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complainttimeline',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complainttimeline',
            name='scheduled_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complainttimeline',
            name='work_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/after/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='damage_type',
            field=models.CharField(choices=[('Pothole', 'Pothole'), ('Crack', 'Crack'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Work Scheduled', 'Work Scheduled'), ('Work Started', 'Work Started'), ('In Progress', 'In Progress'), ('Repair Verification', 'Repair Verification'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Escalated', 'Escalated')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complainttimeline',
            name='officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
